//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfDispatcher")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cliente.ServiceReference1.CacheSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cliente.ServiceReference1.CacheItemPriority))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cliente.ServiceReference1.DateFunctionsTimeMeasuresEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cliente.ServiceReference1.ContextInformation))]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiceReference1.ContextInformation ContextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object EntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cliente.ServiceReference1.CacheSettings CacheField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cliente.ServiceReference1.ContextInformation Context {
            get {
                return this.ContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextField, value) != true)) {
                    this.ContextField = value;
                    this.RaisePropertyChanged("Context");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Cliente.ServiceReference1.CacheSettings Cache {
            get {
                return this.CacheField;
            }
            set {
                if ((object.ReferenceEquals(this.CacheField, value) != true)) {
                    this.CacheField = value;
                    this.RaisePropertyChanged("Cache");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContextInformation", Namespace="http://schemas.datacontract.org/2004/07/Fwk.Bases")]
    [System.SerializableAttribute()]
    public partial class ContextInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string m_HostNameField;
        
        private System.DateTime m_HostTimeField;
        
        private string m_ServerNameField;
        
        private System.DateTime m_ServerTimeField;
        
        private string m_UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_HostName {
            get {
                return this.m_HostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_HostNameField, value) != true)) {
                    this.m_HostNameField = value;
                    this.RaisePropertyChanged("m_HostName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime m_HostTime {
            get {
                return this.m_HostTimeField;
            }
            set {
                if ((this.m_HostTimeField.Equals(value) != true)) {
                    this.m_HostTimeField = value;
                    this.RaisePropertyChanged("m_HostTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_ServerName {
            get {
                return this.m_ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_ServerNameField, value) != true)) {
                    this.m_ServerNameField = value;
                    this.RaisePropertyChanged("m_ServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime m_ServerTime {
            get {
                return this.m_ServerTimeField;
            }
            set {
                if ((this.m_ServerTimeField.Equals(value) != true)) {
                    this.m_ServerTimeField = value;
                    this.RaisePropertyChanged("m_ServerTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_UserName {
            get {
                return this.m_UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_UserNameField, value) != true)) {
                    this.m_UserNameField = value;
                    this.RaisePropertyChanged("m_UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CacheSettings", Namespace="http://schemas.datacontract.org/2004/07/Fwk.HelperFunctions.Caching")]
    [System.SerializableAttribute()]
    public partial class CacheSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _CacheManagerNameField;
        
        private bool _CacheOnClientSideField;
        
        private bool _CacheOnServerSideField;
        
        private double _ExpirationTimeField;
        
        private Cliente.ServiceReference1.CacheItemPriority _PriorityField;
        
        private bool _RefreshOnExpiredField;
        
        private string _ResponseCacheIdField;
        
        private Cliente.ServiceReference1.DateFunctionsTimeMeasuresEnum _TimeMeasuresEnumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _CacheManagerName {
            get {
                return this._CacheManagerNameField;
            }
            set {
                if ((object.ReferenceEquals(this._CacheManagerNameField, value) != true)) {
                    this._CacheManagerNameField = value;
                    this.RaisePropertyChanged("_CacheManagerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _CacheOnClientSide {
            get {
                return this._CacheOnClientSideField;
            }
            set {
                if ((this._CacheOnClientSideField.Equals(value) != true)) {
                    this._CacheOnClientSideField = value;
                    this.RaisePropertyChanged("_CacheOnClientSide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _CacheOnServerSide {
            get {
                return this._CacheOnServerSideField;
            }
            set {
                if ((this._CacheOnServerSideField.Equals(value) != true)) {
                    this._CacheOnServerSideField = value;
                    this.RaisePropertyChanged("_CacheOnServerSide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double _ExpirationTime {
            get {
                return this._ExpirationTimeField;
            }
            set {
                if ((this._ExpirationTimeField.Equals(value) != true)) {
                    this._ExpirationTimeField = value;
                    this.RaisePropertyChanged("_ExpirationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Cliente.ServiceReference1.CacheItemPriority _Priority {
            get {
                return this._PriorityField;
            }
            set {
                if ((this._PriorityField.Equals(value) != true)) {
                    this._PriorityField = value;
                    this.RaisePropertyChanged("_Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _RefreshOnExpired {
            get {
                return this._RefreshOnExpiredField;
            }
            set {
                if ((this._RefreshOnExpiredField.Equals(value) != true)) {
                    this._RefreshOnExpiredField = value;
                    this.RaisePropertyChanged("_RefreshOnExpired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ResponseCacheId {
            get {
                return this._ResponseCacheIdField;
            }
            set {
                if ((object.ReferenceEquals(this._ResponseCacheIdField, value) != true)) {
                    this._ResponseCacheIdField = value;
                    this.RaisePropertyChanged("_ResponseCacheId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Cliente.ServiceReference1.DateFunctionsTimeMeasuresEnum _TimeMeasuresEnum {
            get {
                return this._TimeMeasuresEnumField;
            }
            set {
                if ((this._TimeMeasuresEnumField.Equals(value) != true)) {
                    this._TimeMeasuresEnumField = value;
                    this.RaisePropertyChanged("_TimeMeasuresEnum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CacheItemPriority", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Practices.EnterpriseLibrary.Cac" +
        "hing")]
    public enum CacheItemPriority : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotRemovable = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateFunctions.TimeMeasuresEnum", Namespace="http://schemas.datacontract.org/2004/07/Fwk.HelperFunctions")]
    public enum DateFunctionsTimeMeasuresEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromDays = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromHours = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromMinutes = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FromSeconds = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFwkService1")]
    public interface IFwkService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFwkService1/ExecuteService", ReplyAction="http://tempuri.org/IFwkService1/ExecuteServiceResponse")]
        Cliente.ServiceReference1.CompositeType ExecuteService(Cliente.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFwkService1/ExecuteService", ReplyAction="http://tempuri.org/IFwkService1/ExecuteServiceResponse")]
        System.IAsyncResult BeginExecuteService(Cliente.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState);
        
        Cliente.ServiceReference1.CompositeType EndExecuteService(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IFwkService1Channel : Cliente.ServiceReference1.IFwkService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ExecuteServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExecuteServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Cliente.ServiceReference1.CompositeType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Cliente.ServiceReference1.CompositeType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FwkService1Client : System.ServiceModel.ClientBase<Cliente.ServiceReference1.IFwkService1>, Cliente.ServiceReference1.IFwkService1 {
        
        private BeginOperationDelegate onBeginExecuteServiceDelegate;
        
        private EndOperationDelegate onEndExecuteServiceDelegate;
        
        private System.Threading.SendOrPostCallback onExecuteServiceCompletedDelegate;
        
        public FwkService1Client() {
        }
        
        public FwkService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FwkService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FwkService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FwkService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ExecuteServiceCompletedEventArgs> ExecuteServiceCompleted;
        
        public Cliente.ServiceReference1.CompositeType ExecuteService(Cliente.ServiceReference1.CompositeType composite) {
            return base.Channel.ExecuteService(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginExecuteService(Cliente.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecuteService(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Cliente.ServiceReference1.CompositeType EndExecuteService(System.IAsyncResult result) {
            return base.Channel.EndExecuteService(result);
        }
        
        private System.IAsyncResult OnBeginExecuteService(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Cliente.ServiceReference1.CompositeType composite = ((Cliente.ServiceReference1.CompositeType)(inValues[0]));
            return this.BeginExecuteService(composite, callback, asyncState);
        }
        
        private object[] OnEndExecuteService(System.IAsyncResult result) {
            Cliente.ServiceReference1.CompositeType retVal = this.EndExecuteService(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExecuteServiceCompleted(object state) {
            if ((this.ExecuteServiceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecuteServiceCompleted(this, new ExecuteServiceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecuteServiceAsync(Cliente.ServiceReference1.CompositeType composite) {
            this.ExecuteServiceAsync(composite, null);
        }
        
        public void ExecuteServiceAsync(Cliente.ServiceReference1.CompositeType composite, object userState) {
            if ((this.onBeginExecuteServiceDelegate == null)) {
                this.onBeginExecuteServiceDelegate = new BeginOperationDelegate(this.OnBeginExecuteService);
            }
            if ((this.onEndExecuteServiceDelegate == null)) {
                this.onEndExecuteServiceDelegate = new EndOperationDelegate(this.OnEndExecuteService);
            }
            if ((this.onExecuteServiceCompletedDelegate == null)) {
                this.onExecuteServiceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteServiceCompleted);
            }
            base.InvokeAsync(this.onBeginExecuteServiceDelegate, new object[] {
                        composite}, this.onEndExecuteServiceDelegate, this.onExecuteServiceCompletedDelegate, userState);
        }
    }
}
