//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfDispatcher")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Fwk.HelperFunctions.Caching.CacheSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cliente.ServiceReference1.Survey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Cliente.ServiceReference1.CacheItemPriority))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Fwk.HelperFunctions.DateFunctions.TimeMeasuresEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Fwk.Bases.ContextInformation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Fwk.Bases.Entity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Fwk.Bases.EntityState))]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object EntityFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fwk.Bases.ContextInformation ContextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Fwk.HelperFunctions.Caching.CacheSettings CacheField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object EntityField {
            get {
                return this.EntityFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityFieldField, value) != true)) {
                    this.EntityFieldField = value;
                    this.RaisePropertyChanged("EntityField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Fwk.Bases.ContextInformation Context {
            get {
                return this.ContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextField, value) != true)) {
                    this.ContextField = value;
                    this.RaisePropertyChanged("Context");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Fwk.HelperFunctions.Caching.CacheSettings Cache {
            get {
                return this.CacheField;
            }
            set {
                if ((object.ReferenceEquals(this.CacheField, value) != true)) {
                    this.CacheField = value;
                    this.RaisePropertyChanged("Cache");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Survey", Namespace="http://schemas.datacontract.org/2004/07/WcfCommon")]
    [System.SerializableAttribute()]
    public partial class Survey : Fwk.Bases.Entity, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<bool> _ActiveFlagField;
        
        private string _DescriptionField;
        
        private int _ModifiedByUserIdField;
        
        private string _ModifiedByUserNameField;
        
        private System.Nullable<System.DateTime> _ModifiedDateField;
        
        private string _NameField;
        
        private int _SurveyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> _ActiveFlag {
            get {
                return this._ActiveFlagField;
            }
            set {
                if ((this._ActiveFlagField.Equals(value) != true)) {
                    this._ActiveFlagField = value;
                    this.RaisePropertyChanged("_ActiveFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Description {
            get {
                return this._DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this._DescriptionField, value) != true)) {
                    this._DescriptionField = value;
                    this.RaisePropertyChanged("_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _ModifiedByUserId {
            get {
                return this._ModifiedByUserIdField;
            }
            set {
                if ((this._ModifiedByUserIdField.Equals(value) != true)) {
                    this._ModifiedByUserIdField = value;
                    this.RaisePropertyChanged("_ModifiedByUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ModifiedByUserName {
            get {
                return this._ModifiedByUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this._ModifiedByUserNameField, value) != true)) {
                    this._ModifiedByUserNameField = value;
                    this.RaisePropertyChanged("_ModifiedByUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _ModifiedDate {
            get {
                return this._ModifiedDateField;
            }
            set {
                if ((this._ModifiedDateField.Equals(value) != true)) {
                    this._ModifiedDateField = value;
                    this.RaisePropertyChanged("_ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Name {
            get {
                return this._NameField;
            }
            set {
                if ((object.ReferenceEquals(this._NameField, value) != true)) {
                    this._NameField = value;
                    this.RaisePropertyChanged("_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _SurveyId {
            get {
                return this._SurveyIdField;
            }
            set {
                if ((this._SurveyIdField.Equals(value) != true)) {
                    this._SurveyIdField = value;
                    this.RaisePropertyChanged("_SurveyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CacheItemPriority", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Practices.EnterpriseLibrary.Cac" +
        "hing")]
    public enum CacheItemPriority : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotRemovable = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFwkService1")]
    public interface IFwkService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFwkService1/ExecuteService", ReplyAction="http://tempuri.org/IFwkService1/ExecuteServiceResponse")]
        Cliente.ServiceReference1.CompositeType ExecuteService(Cliente.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IFwkService1/ExecuteService", ReplyAction="http://tempuri.org/IFwkService1/ExecuteServiceResponse")]
        System.IAsyncResult BeginExecuteService(Cliente.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState);
        
        Cliente.ServiceReference1.CompositeType EndExecuteService(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IFwkService1Channel : Cliente.ServiceReference1.IFwkService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ExecuteServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExecuteServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Cliente.ServiceReference1.CompositeType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Cliente.ServiceReference1.CompositeType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FwkService1Client : System.ServiceModel.ClientBase<Cliente.ServiceReference1.IFwkService1>, Cliente.ServiceReference1.IFwkService1 {
        
        private BeginOperationDelegate onBeginExecuteServiceDelegate;
        
        private EndOperationDelegate onEndExecuteServiceDelegate;
        
        private System.Threading.SendOrPostCallback onExecuteServiceCompletedDelegate;
        
        public FwkService1Client() {
        }
        
        public FwkService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FwkService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FwkService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FwkService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ExecuteServiceCompletedEventArgs> ExecuteServiceCompleted;
        
        public Cliente.ServiceReference1.CompositeType ExecuteService(Cliente.ServiceReference1.CompositeType composite) {
            return base.Channel.ExecuteService(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginExecuteService(Cliente.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecuteService(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Cliente.ServiceReference1.CompositeType EndExecuteService(System.IAsyncResult result) {
            return base.Channel.EndExecuteService(result);
        }
        
        private System.IAsyncResult OnBeginExecuteService(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Cliente.ServiceReference1.CompositeType composite = ((Cliente.ServiceReference1.CompositeType)(inValues[0]));
            return this.BeginExecuteService(composite, callback, asyncState);
        }
        
        private object[] OnEndExecuteService(System.IAsyncResult result) {
            Cliente.ServiceReference1.CompositeType retVal = this.EndExecuteService(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExecuteServiceCompleted(object state) {
            if ((this.ExecuteServiceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecuteServiceCompleted(this, new ExecuteServiceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecuteServiceAsync(Cliente.ServiceReference1.CompositeType composite) {
            this.ExecuteServiceAsync(composite, null);
        }
        
        public void ExecuteServiceAsync(Cliente.ServiceReference1.CompositeType composite, object userState) {
            if ((this.onBeginExecuteServiceDelegate == null)) {
                this.onBeginExecuteServiceDelegate = new BeginOperationDelegate(this.OnBeginExecuteService);
            }
            if ((this.onEndExecuteServiceDelegate == null)) {
                this.onEndExecuteServiceDelegate = new EndOperationDelegate(this.OnEndExecuteService);
            }
            if ((this.onExecuteServiceCompletedDelegate == null)) {
                this.onExecuteServiceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteServiceCompleted);
            }
            base.InvokeAsync(this.onBeginExecuteServiceDelegate, new object[] {
                        composite}, this.onEndExecuteServiceDelegate, this.onExecuteServiceCompletedDelegate, userState);
        }
    }
}
