<?xml version="1.0" encoding="utf-8"?>
<Database Name="fwktest" Class="configdataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SANTANA\SQLEXPRESS;Initial Catalog=fwktest;Integrated Security=True" SettingsObjectName="Fwk.Bases.Properties.Settings" SettingsPropertyName="fwktestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.fwk_ConfigMannager" Member="fwk_ConfigMannagers">
    <Type Name="fwk_ConfigMannager">
      <Column Name="ConfigurationFileName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[group]" Member="group" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[key]" Member="key" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="encrypted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>