
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Prominente Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using Fwk.Bases;
using Fwk.Security.BE;
using Fwk.Security;
using Fwk.Security.ISVC.SearchUsersByParam;



namespace Fwk.Security.SVC
{

    public class SearchUsersByParamService : BusinessService<SearchUsersByParamRequest, SearchUsersByParamResponse>
    {
        public override SearchUsersByParamResponse Execute(SearchUsersByParamRequest pServiceRequest)
        {
            SearchUsersByParamResponse wRes = new SearchUsersByParamResponse();
            //Implement your code here
            return wRes;
        }
    }
}
        