//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralizedSecurity.W32.Test.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoogonUserResult", Namespace="http://schemas.datacontract.org/2004/07/CentralizedSecurity.wcf.Contracts")]
    [System.SerializableAttribute()]
    public partial class LoogonUserResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Autenticated {
            get {
                return this.AutenticatedField;
            }
            set {
                if ((this.AutenticatedField.Equals(value) != true)) {
                    this.AutenticatedField = value;
                    this.RaisePropertyChanged("Autenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogResult {
            get {
                return this.LogResultField;
            }
            set {
                if ((object.ReferenceEquals(this.LogResultField, value) != true)) {
                    this.LogResultField = value;
                    this.RaisePropertyChanged("LogResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICoreSecurity")]
    public interface ICoreSecurity {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreSecurity/Authenticate", ReplyAction="http://tempuri.org/ICoreSecurity/AuthenticateResponse")]
        CentralizedSecurity.W32.Test.ServiceReference1.LoogonUserResult Authenticate(string userName, string password, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreSecurity/GetDomainNames", ReplyAction="http://tempuri.org/ICoreSecurity/GetDomainNamesResponse")]
        string GetDomainNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoreSecurity/Test", ReplyAction="http://tempuri.org/ICoreSecurity/TestResponse")]
        string Test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoreSecurityChannel : CentralizedSecurity.W32.Test.ServiceReference1.ICoreSecurity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreSecurityClient : System.ServiceModel.ClientBase<CentralizedSecurity.W32.Test.ServiceReference1.ICoreSecurity>, CentralizedSecurity.W32.Test.ServiceReference1.ICoreSecurity {
        
        public CoreSecurityClient() {
        }
        
        public CoreSecurityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreSecurityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreSecurityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreSecurityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CentralizedSecurity.W32.Test.ServiceReference1.LoogonUserResult Authenticate(string userName, string password, string domain) {
            return base.Channel.Authenticate(userName, password, domain);
        }
        
        public string GetDomainNames() {
            return base.Channel.GetDomainNames();
        }
        
        public string Test() {
            return base.Channel.Test();
        }
    }
}
