
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Fwk Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Fwk.Bases;
using System.Xml.Serialization;
using Fwk.Security;
using Fwk.Security.BE;


namespace Fwk.Security.ISVC.CreateRulesCategory
{

    [Serializable]
    public class CreateRulesCategoryReq : Request<FwkCategory>
    {
        public CreateRulesCategoryReq()
        {
            this.ServiceName = "CreateRulesCategoryService";
        }
    }
    [Serializable]
    public class CreateRulesCategoryRes : Response<Result>
    {
    }

    [XmlInclude(typeof(Result))]
    public class Result : Entity
    {
        int id;

        public int Id
        {
            get { return id; }
            set { id = value; }
        }
    }

   


}
