
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Fwk Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using Fwk.Bases;
using Fwk.Security.BE;
using Fwk.Security;
using  Fwk.Security.ISVC.CreateRules;
using Fwk.Security.BC;



namespace Fwk.Security.SVC
{
    /// <summary>
    /// Servicio que crea una nueva regla
    /// </summary>
    public class CreateRuleService : BusinessService<CreateRuleReq, CreateRuleRes>
    {
        public override CreateRuleRes Execute(CreateRuleReq pServiceRequest)
        {
            CreateRuleRes wRes = new CreateRuleRes();
            FwkAuthorizationRule pFwkAuthorizationRule = new FwkAuthorizationRule(pServiceRequest.BusinessData);
            FwkMembership.CreateRule(pFwkAuthorizationRule, pServiceRequest.SecurityProviderName);  
            return wRes;
        }
    }
}
