<?xml version="1.0" encoding="utf-8"?>
<Database Name="Gastos" Class="TraceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KATY\SQLEXPRESS;Initial Catalog=FWKTRACE;Integrated Security=True" SettingsObjectName="FwkSqlTrace.Properties.Settings" SettingsPropertyName="GastosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.trace" Member="Traces">
    <Type Name="Trace">
      <Column Name="RowNumber" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventClass" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TextData" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="NTUserName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="LoginName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="CPU" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reads" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Writes" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ClientProcessID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SPID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>