
        //------------------------------------------------------------------------------
        // <auto-generated>
          //     This code was generated by a Prominente Code Generator.
          //     Runtime Version:1.0
          //
          //     Changes to this file may cause incorrect behavior and will be lost if
          //     the code is regenerated.
          //
        //</auto-generated>
        //------------------------------------------------------------------------------


using System;
using System.Data;
using Fwk.Bases;
using Fwk.Security.BE;
using Fwk.Security.ISVC.DeleteRulesCategory;
using Fwk.Security;
using Fwk.Security.BC;

namespace Fwk.Security.SVC
{

    public class DeleteRulesCategoryService : BusinessService<DeleteRulesCategoryRequest, DeleteRulesCategoryResponse>
    {

        public override DeleteRulesCategoryResponse Execute(DeleteRulesCategoryRequest pServiceRequest)
        {
            
            DeleteRulesCategoryResponse wRes = new DeleteRulesCategoryResponse();

            RulesCategoryBC wRulesCategoryBC = new RulesCategoryBC(pServiceRequest.ContextInformation.CompanyId, pServiceRequest.SecurityProviderName);
            wRulesCategoryBC.Delete(pServiceRequest.BusinessData.CategoryId.Value);

            return wRes;
        }
    }
}
        