
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Prominente Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Web.Security;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using Microsoft.Practices.EnterpriseLibrary.Common.Configuration;
using Microsoft.Practices.EnterpriseLibrary.Security;
using Fwk.Bases;
using Fwk.Security.BE;
using Fwk.Security;
using Fwk.Security.ISVC.GetAuthorizationRules;



namespace Fwk.Security.SVC
{

    /// <summary>
    /// 
    /// </summary>
    public class GetAuthorizationRulesService : BusinessService<GetAuthorizationRulesReq, GetAuthorizationRulesRes>
    {
        public override GetAuthorizationRulesRes Execute(GetAuthorizationRulesReq pServiceRequest)
        {
            GetAuthorizationRulesRes wRes = new GetAuthorizationRulesRes();

            //TODO: Determonar correcto nombre del servicio ..parece el mismo qu e GetAllRulesService.cs
            FwkAuthorizationRuleList rules = FwkMembership.GetRulesAuxList(pServiceRequest.SecurityProviderName);



             wRes.BusinessData.Rules = rules;

            return wRes;
        }

       
    }
}
        