<?xml version="1.0" encoding="utf-8"?><Database Name="BB_Desarrollo_5_0" Class="ConfigDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.fwk_ConfigManager" Member="fwk_ConfigManagers">
    <Type Name="fwk_ConfigManager">
      <Column Name="ConfigurationFileName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[group]" Member="group" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[key]" Member="key" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="encrypted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Campaings.ParamCampaings" Member="ParamCampaings">
    <Type Name="ParamCampaing">
      <Column Name="ParamCapaingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ParamCampaingIdRelated" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.fwk_ConfigManager_PIVOT" Method="fwk_ConfigManager_PIVOT">
    <Parameter Name="columns2" Type="System.String" DbType="VarChar(2000)" />
    <Return Type="System.Int32" />
  </Function>
</Database>