//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by  Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Fwk.Bases;
using System.Xml.Serialization;

namespace Fwk.Security.BE
{
    [XmlRoot("TeamLogList"), SerializableAttribute]
    public class TeamLogList : Entities<TeamLogBE>
    {
        #region [Methods]
        /// <summary>
        /// Metodo estatico que retorna un objeto TeamLogList apartir de un xml.-
        /// </summary>
        /// <param name="pXml">String con el xml</param>
        /// <returns>TeamLogList</returns>
        public static TeamLogList GetTeamLogListFromXml(String pXml)
        {
            return (TeamLogList)Entity.GetObjectFromXml(typeof(TeamLogList), pXml);
        }
        #endregion
    }

    [XmlInclude(typeof(TeamLogBE)), Serializable]
    public class TeamLogBE : Entity
    {
        #region [Private Members]
        private System.Int32? mi_TeamLogId;
        private System.Int32? mi_SuperiorId;
        private System.String msz_SuperiorName;
        private System.String msz_SuperiorFirstName;
        private System.String msz_SuperiorLastName;
        private System.Int32? mi_UserId;
        private System.String msz_UserName;
        private System.String msz_UserFirstName;
        private System.String msz_UserLastName;
        private System.DateTime? mdt_StartDate;
        private System.Int32? mi_TeamLevel;
        private System.DateTime? mdt_ModifiedDate;
        private System.Int32? mi_ModifiedByUserId;
        private System.String msz_ModifiedByUserName;

        #endregion

        #region [Properties]

        #region [TeamLogId]
        [XmlElement(ElementName = "TeamLogId", DataType = "int")]
        public System.Int32? TeamLogId
        {
            get { return mi_TeamLogId; }
            set { mi_TeamLogId = value; }
        }
        #endregion
        #region [SuperiorId]
        [XmlElement(ElementName = "SuperiorId", DataType = "int")]
        public System.Int32? SuperiorId
        {
            get { return mi_SuperiorId; }
            set { mi_SuperiorId = value; }
        }
        #endregion
        #region [SuperiorName]
        [XmlElement(ElementName = "SuperiorName", DataType = "string")]
        public System.String SuperiorName
        {
            get { return msz_SuperiorName; }
            set { msz_SuperiorName = value; }
        }
        #endregion
        #region [SuperiorFirstName]
        [XmlElement(ElementName = "SuperiorFirstName", DataType = "string")]
        public System.String SuperiorFirstName
        {
            get { return msz_SuperiorFirstName; }
            set { msz_SuperiorFirstName = value; }
        }
        #endregion
        #region [SuperiorLastName]
        [XmlElement(ElementName = "SuperiorLastName", DataType = "string")]
        public System.String SuperiorLastName
        {
            get { return msz_SuperiorLastName; }
            set { msz_SuperiorLastName = value; }
        }
        #endregion
        #region [UserId]
        [XmlElement(ElementName = "UserId", DataType = "int")]
        public System.Int32? UserId
        {
            get { return mi_UserId; }
            set { mi_UserId = value; }
        }
        #endregion
        #region [UserName]
        [XmlElement(ElementName = "UserName", DataType = "string")]
        public System.String UserName
        {
            get { return msz_UserName; }
            set { msz_UserName = value; }
        }
        #endregion
        #region [UserFirstName]
        [XmlElement(ElementName = "UserFirstName", DataType = "string")]
        public System.String UserFirstName
        {
            get { return msz_UserFirstName; }
            set { msz_UserFirstName = value; }
        }
        #endregion
        #region [UserLastName]
        [XmlElement(ElementName = "UserLastName", DataType = "string")]
        public System.String UserLastName
        {
            get { return msz_UserLastName; }
            set { msz_UserLastName = value; }
        }
        #endregion
        #region [StartDate]
        [XmlElement(ElementName = "StartDate", DataType = "dateTime")]
        public System.DateTime? StartDate
        {
            get { return mdt_StartDate; }
            set { mdt_StartDate = value; }
        }
        #endregion
        #region [TeamLevel]
        [XmlElement(ElementName = "TeamLevel", DataType = "int")]
        public System.Int32? TeamLevel
        {
            get { return mi_TeamLevel; }
            set { mi_TeamLevel = value; }
        }
        #endregion
        #region [ModifiedDate]
        [XmlElement(ElementName = "ModifiedDate", DataType = "dateTime")]
        public System.DateTime? ModifiedDate
        {
            get { return mdt_ModifiedDate; }
            set { mdt_ModifiedDate = value; }
        }
        #endregion
        #region [ModifiedByUserId]
        [XmlElement(ElementName = "ModifiedByUserId", DataType = "int")]
        public System.Int32? ModifiedByUserId
        {
            get { return mi_ModifiedByUserId; }
            set { mi_ModifiedByUserId = value; }
        }
        #endregion
        #region [ModifiedByUserName]
        [XmlElement(ElementName = "ModifiedByUserName", DataType = "string")]
        public System.String ModifiedByUserName
        {
            get { return msz_ModifiedByUserName; }
            set { msz_ModifiedByUserName = value; }
        }
        #endregion

        #endregion

        #region [Methods]
        /// <summary>
        /// Metodo estatico que retorna un objeto TeamLogBE apartir de un xml.-
        /// </summary>
        /// <param name="pXml">String con el xml</param>
        /// <returns>TeamLogBE</returns>
        public static TeamLogBE GetTeamLogBEFromXml(String pXml)
        {
            return (TeamLogBE)Entity.GetObjectFromXml(typeof(TeamLogBE), pXml);
        }
        #endregion
    }
}