//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fwk.Security.Admin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fwk.Security.Admin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _177 {
            get {
                object obj = ResourceManager.GetObject("_177", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _177Left {
            get {
                object obj = ResourceManager.GetObject("_177Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap access_control_ok_32 {
            get {
                object obj = ResourceManager.GetObject("access_control_ok_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user name and select or enter a role..
        /// </summary>
        internal static string AddUserRoleErrorMessage {
            get {
                return ResourceManager.GetString("AddUserRoleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {1} added for user {0}..
        /// </summary>
        internal static string AddUserRoleMessage {
            get {
                return ResourceManager.GetString("AddUserRoleMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap admin_16 {
            get {
                object obj = ResourceManager.GetObject("admin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap admin_24 {
            get {
                object obj = ResourceManager.GetObject("admin_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap admin_32 {
            get {
                object obj = ResourceManager.GetObject("admin_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_list_add_32 {
            get {
                object obj = ResourceManager.GetObject("application_list_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap apply_16 {
            get {
                object obj = ResourceManager.GetObject("apply_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap apply_24 {
            get {
                object obj = ResourceManager.GetObject("apply_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap apply_32 {
            get {
                object obj = ResourceManager.GetObject("apply_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate user.
        /// </summary>
        internal static string AuthenticateTitleMessage {
            get {
                return ResourceManager.GetString("AuthenticateTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization rule {0} not found in configuration..
        /// </summary>
        internal static string AuthorizationRuleNotFoundMsg {
            get {
                return ResourceManager.GetString("AuthorizationRuleNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task: {0}
        ///Result: {1}.
        /// </summary>
        internal static string AzManResultMessage {
            get {
                return ResourceManager.GetString("AzManResultMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Button_ok {
            get {
                object obj = ResourceManager.GetObject("Button_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel_16 {
            get {
                object obj = ResourceManager.GetObject("cancel_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel_2_16 {
            get {
                object obj = ResourceManager.GetObject("Cancel_2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel_2_24 {
            get {
                object obj = ResourceManager.GetObject("Cancel_2_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel_2_32 {
            get {
                object obj = ResourceManager.GetObject("Cancel_2_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel_24 {
            get {
                object obj = ResourceManager.GetObject("cancel_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel_32 {
            get {
                object obj = ResourceManager.GetObject("cancel_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking roles for &quot;{0}&quot;.
        /// </summary>
        internal static string CheckingRolesMessage {
            get {
                return ResourceManager.GetString("CheckingRolesMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Close_16 {
            get {
                object obj = ResourceManager.GetObject("Close_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Close_24 {
            get {
                object obj = ResourceManager.GetObject("Close_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Close_32 {
            get {
                object obj = ResourceManager.GetObject("Close_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseImage {
            get {
                object obj = ResourceManager.GetObject("CloseImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapce_16 {
            get {
                object obj = ResourceManager.GetObject("collapce_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapseVertical_16 {
            get {
                object obj = ResourceManager.GetObject("collapseVertical_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap collapseVertical_24 {
            get {
                object obj = ResourceManager.GetObject("collapseVertical_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connection_Check {
            get {
                object obj = ResourceManager.GetObject("Connection_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connection_Error {
            get {
                object obj = ResourceManager.GetObject("Connection_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connection_Warning {
            get {
                object obj = ResourceManager.GetObject("Connection_Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_16 {
            get {
                object obj = ResourceManager.GetObject("copy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_24 {
            get {
                object obj = ResourceManager.GetObject("copy_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_32 {
            get {
                object obj = ResourceManager.GetObject("copy_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_48 {
            get {
                object obj = ResourceManager.GetObject("copy_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity was added to the cache and can be retrieved using the token {0}.
        /// </summary>
        internal static string CreateTokenMessage {
            get {
                return ResourceManager.GetString("CreateTokenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a token for non-authenticated user. This scenario requires running the &quot;Authenticate user using credentials&quot; scenario first.
        /// </summary>
        internal static string CreateTokenRequiresIdentityMessage {
            get {
                return ResourceManager.GetString("CreateTokenRequiresIdentityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new user.
        /// </summary>
        internal static string CreateUserTitleMessage {
            get {
                return ResourceManager.GetString("CreateUserTitleMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap db {
            get {
                object obj = ResourceManager.GetObject("db", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dbs {
            get {
                object obj = ResourceManager.GetObject("dbs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user name..
        /// </summary>
        internal static string DeleteUserErrorMessage {
            get {
                return ResourceManager.GetString("DeleteUserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} deleted..
        /// </summary>
        internal static string DeleteUserMessage {
            get {
                return ResourceManager.GetString("DeleteUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user name and a role..
        /// </summary>
        internal static string DeleteUserRoleErrorMessage {
            get {
                return ResourceManager.GetString("DeleteUserRoleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {1} deleted for user {0}..
        /// </summary>
        internal static string DeleteUserRoleMessage {
            get {
                return ResourceManager.GetString("DeleteUserRoleMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap error_16 {
            get {
                object obj = ResourceManager.GetObject("error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_24 {
            get {
                object obj = ResourceManager.GetObject("error_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_32 {
            get {
                object obj = ResourceManager.GetObject("error_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Excel_16x16 {
            get {
                object obj = ResourceManager.GetObject("Excel_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exclamation_16 {
            get {
                object obj = ResourceManager.GetObject("exclamation_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exclamation_24 {
            get {
                object obj = ResourceManager.GetObject("exclamation_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exclamation_32 {
            get {
                object obj = ResourceManager.GetObject("exclamation_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exclamation_48 {
            get {
                object obj = ResourceManager.GetObject("exclamation_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Expand_16 {
            get {
                object obj = ResourceManager.GetObject("Expand_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expandVertical_16 {
            get {
                object obj = ResourceManager.GetObject("expandVertical_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expandVertical_24 {
            get {
                object obj = ResourceManager.GetObject("expandVertical_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the identity. The supplied token is expired..
        /// </summary>
        internal static string ExpiredTokenErrorMessage {
            get {
                return ResourceManager.GetString("ExpiredTokenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot expire token because it couldn&apos;t be created..
        /// </summary>
        internal static string ExpireTokenErrorMessage {
            get {
                return ResourceManager.GetString("ExpireTokenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token was expired..
        /// </summary>
        internal static string ExpireTokenMessage {
            get {
                return ResourceManager.GetString("ExpireTokenMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Explorer_16x16 {
            get {
                object obj = ResourceManager.GetObject("Explorer_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_add_16 {
            get {
                object obj = ResourceManager.GetObject("file_add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_add_32 {
            get {
                object obj = ResourceManager.GetObject("file_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_apply_16 {
            get {
                object obj = ResourceManager.GetObject("file_apply_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_apply_32 {
            get {
                object obj = ResourceManager.GetObject("file_apply_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_cancel_16 {
            get {
                object obj = ResourceManager.GetObject("file_cancel_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_cancel_24 {
            get {
                object obj = ResourceManager.GetObject("file_cancel_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_cancel_32 {
            get {
                object obj = ResourceManager.GetObject("file_cancel_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_cancel_48 {
            get {
                object obj = ResourceManager.GetObject("file_cancel_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_de_24 {
            get {
                object obj = ResourceManager.GetObject("file_de_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_del_16 {
            get {
                object obj = ResourceManager.GetObject("file_del_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_del_32 {
            get {
                object obj = ResourceManager.GetObject("file_del_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_del_48 {
            get {
                object obj = ResourceManager.GetObject("file_del_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_edit_16 {
            get {
                object obj = ResourceManager.GetObject("file_edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_edit_24 {
            get {
                object obj = ResourceManager.GetObject("file_edit_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_edit_32 {
            get {
                object obj = ResourceManager.GetObject("file_edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_edit_48 {
            get {
                object obj = ResourceManager.GetObject("file_edit_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_find_16 {
            get {
                object obj = ResourceManager.GetObject("file_find_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_find_24 {
            get {
                object obj = ResourceManager.GetObject("file_find_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_find_32 {
            get {
                object obj = ResourceManager.GetObject("file_find_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_find_48 {
            get {
                object obj = ResourceManager.GetObject("file_find_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_new_16 {
            get {
                object obj = ResourceManager.GetObject("file_new_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_new_32 {
            get {
                object obj = ResourceManager.GetObject("file_new_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_new_16 {
            get {
                object obj = ResourceManager.GetObject("folder_new_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_new_24 {
            get {
                object obj = ResourceManager.GetObject("folder_new_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_new_32 {
            get {
                object obj = ResourceManager.GetObject("folder_new_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fwk_delete_16x {
            get {
                object obj = ResourceManager.GetObject("fwk_delete_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fwk_Refresh {
            get {
                object obj = ResourceManager.GetObject("fwk_Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help__Alt_2__16 {
            get {
                object obj = ResourceManager.GetObject("Help__Alt_2__16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help__Alt_2__24 {
            get {
                object obj = ResourceManager.GetObject("Help__Alt_2__24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help__Alt_2__32 {
            get {
                object obj = ResourceManager.GetObject("Help__Alt_2__32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_16 {
            get {
                object obj = ResourceManager.GetObject("help_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_24 {
            get {
                object obj = ResourceManager.GetObject("help_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_32 {
            get {
                object obj = ResourceManager.GetObject("help_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_48 {
            get {
                object obj = ResourceManager.GetObject("help_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap html_16x16 {
            get {
                object obj = ResourceManager.GetObject("html_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity: {0}.
        /// </summary>
        internal static string IdentityMessage {
            get {
                return ResourceManager.GetString("IdentityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name and select a role and a rule..
        /// </summary>
        internal static string IdentityRoleErrorMessage {
            get {
                return ResourceManager.GetString("IdentityRoleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: {0}
        ///Role: {1}.
        /// </summary>
        internal static string IdentityRoleMessage {
            get {
                return ResourceManager.GetString("IdentityRoleMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap impt_24 {
            get {
                object obj = ResourceManager.GetObject("impt_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information_16 {
            get {
                object obj = ResourceManager.GetObject("information_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information_24 {
            get {
                object obj = ResourceManager.GetObject("information_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information_32 {
            get {
                object obj = ResourceManager.GetObject("information_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information_48 {
            get {
                object obj = ResourceManager.GetObject("information_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authenticate user {0}. Either the username does not exist in database or the provided password is not correct.
        /// </summary>
        internal static string InvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("InvalidCredentialsMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap lock_16 {
            get {
                object obj = ResourceManager.GetObject("lock_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_24 {
            get {
                object obj = ResourceManager.GetObject("lock_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_32 {
            get {
                object obj = ResourceManager.GetObject("lock_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_16 {
            get {
                object obj = ResourceManager.GetObject("mail_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_24 {
            get {
                object obj = ResourceManager.GetObject("mail_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_32 {
            get {
                object obj = ResourceManager.GetObject("mail_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_48 {
            get {
                object obj = ResourceManager.GetObject("mail_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_16 {
            get {
                object obj = ResourceManager.GetObject("map_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_161 {
            get {
                object obj = ResourceManager.GetObject("map_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_32 {
            get {
                object obj = ResourceManager.GetObject("map_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map_321 {
            get {
                object obj = ResourceManager.GetObject("map_321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaxImage {
            get {
                object obj = ResourceManager.GetObject("MaxImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MinImage {
            get {
                object obj = ResourceManager.GetObject("MinImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap note_16x16 {
            get {
                object obj = ResourceManager.GetObject("note_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should authenticate a user first..
        /// </summary>
        internal static string NullIdentityMessage {
            get {
                return ResourceManager.GetString("NullIdentityMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon page_excel_16x16 {
            get {
                object obj = ResourceManager.GetObject("page_excel_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PDF_16x16 {
            get {
                object obj = ResourceManager.GetObject("PDF_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a profile for current user. You can create a profile by using the &quot;Write profile information about a user&quot; button..
        /// </summary>
        internal static string ProfileNotFoundMessage {
            get {
                return ResourceManager.GetString("ProfileNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name: {0}
        ///  Last Name: {1}
        ///  Preferred Theme: {2}.
        /// </summary>
        internal static string ProfileStringMessage {
            get {
                return ResourceManager.GetString("ProfileStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile has been saved for &quot;{0}&quot;
        ///.
        /// </summary>
        internal static string ProfileUpdatedMessage {
            get {
                return ResourceManager.GetString("ProfileUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some problems while trying to use the Security Quick Start, please check the following error messages: 
        ///
        ///{0}
        ///
        ///This QuickStart requires a database configured with the ASP.NET services schema. Please make sure the database has been initialized using the aspnet_regsql.exe script, and that the QuickStart&apos;s app.config file contains the correct database connection string..
        /// </summary>
        internal static string QuickStartErrorMessage {
            get {
                return ResourceManager.GetString("QuickStartErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        internal static string QuickStartErrorTitle {
            get {
                return ResourceManager.GetString("QuickStartErrorTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve identity because the token doesn&apos;t exist..
        /// </summary>
        internal static string RetrieveIdentityErrorMessage {
            get {
                return ResourceManager.GetString("RetrieveIdentityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity with the following information was retrieved using the token
        ///	Name: {0}
        ///	Authorization Type: {1}.
        /// </summary>
        internal static string RetrieveIdentityMessage {
            get {
                return ResourceManager.GetString("RetrieveIdentityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} created..
        /// </summary>
        internal static string RolCreatedMessage {
            get {
                return ResourceManager.GetString("RolCreatedMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap roles_32 {
            get {
                object obj = ResourceManager.GetObject("roles_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule {0} created.-.
        /// </summary>
        internal static string RuleCreatedMessage {
            get {
                return ResourceManager.GetString("RuleCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule: {0}
        ///Result: user is not authorized.
        /// </summary>
        internal static string RuleResultFalseMessage {
            get {
                return ResourceManager.GetString("RuleResultFalseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule: {0}
        ///Result: user is authorized.
        /// </summary>
        internal static string RuleResultTrueMessage {
            get {
                return ResourceManager.GetString("RuleResultTrueMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap save_16 {
            get {
                object obj = ResourceManager.GetObject("save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_24 {
            get {
                object obj = ResourceManager.GetObject("save_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_32 {
            get {
                object obj = ResourceManager.GetObject("save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_48 {
            get {
                object obj = ResourceManager.GetObject("save_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_16 {
            get {
                object obj = ResourceManager.GetObject("save_as_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_2_16 {
            get {
                object obj = ResourceManager.GetObject("save_as_2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_2_24 {
            get {
                object obj = ResourceManager.GetObject("save_as_2_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_2_32 {
            get {
                object obj = ResourceManager.GetObject("save_as_2_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_2_48 {
            get {
                object obj = ResourceManager.GetObject("save_as_2_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_24 {
            get {
                object obj = ResourceManager.GetObject("save_as_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_32 {
            get {
                object obj = ResourceManager.GetObject("save_as_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_as_48 {
            get {
                object obj = ResourceManager.GetObject("save_as_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_16 {
            get {
                object obj = ResourceManager.GetObject("search_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_24 {
            get {
                object obj = ResourceManager.GetObject("search_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_32 {
            get {
                object obj = ResourceManager.GetObject("search_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sitebuild_icon {
            get {
                object obj = ResourceManager.GetObject("sitebuild_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap srch_16 {
            get {
                object obj = ResourceManager.GetObject("srch_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap srch_32 {
            get {
                object obj = ResourceManager.GetObject("srch_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Thumbs {
            get {
                object obj = ResourceManager.GetObject("Thumbs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trash_16 {
            get {
                object obj = ResourceManager.GetObject("trash_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trash_24 {
            get {
                object obj = ResourceManager.GetObject("trash_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trash_241 {
            get {
                object obj = ResourceManager.GetObject("trash_241", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trash_32 {
            get {
                object obj = ResourceManager.GetObject("trash_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ulock_16 {
            get {
                object obj = ResourceManager.GetObject("ulock_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ulock_24 {
            get {
                object obj = ResourceManager.GetObject("ulock_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ulock_32 {
            get {
                object obj = ResourceManager.GetObject("ulock_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} created..
        /// </summary>
        internal static string UserCreatedMessage {
            get {
                return ResourceManager.GetString("UserCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following profile has been read for &quot;{0}&quot;
        ///  {1}
        ///.
        /// </summary>
        internal static string UserProfileMessage {
            get {
                return ResourceManager.GetString("UserProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Member of role {0}: {1}.
        /// </summary>
        internal static string UserRoleMessage {
            get {
                return ResourceManager.GetString("UserRoleMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Users {
            get {
                object obj = ResourceManager.GetObject("Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully authenticated user {0}.
        /// </summary>
        internal static string ValidCredentialsMessage {
            get {
                return ResourceManager.GetString("ValidCredentialsMessage", resourceCulture);
            }
        }
    }
}
