//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Prominente Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Fwk.Bases;
using System.Xml.Serialization;
using System.Xml;
using Fwk.Security.BE;
using Fwk.Security.Common;

namespace Fwk.Security.ISVC.CreateUsers
{

    [Serializable]
    public class CreateUsersRequest : Request<Param>
    {
        public CreateUsersRequest()
        {
            this.ServiceName = "CreateUsersService";
        }
    }
    [XmlInclude(typeof(Param)), Serializable]
    public class Param : Entity
    {
        #region [Private Members]
        UsersBE _UsersBE;
        private RolList _RolList = new RolList();

        private System.String _ApplicationName;


        #endregion

        #region [Properties]

        #region [Username]

        public UsersBE UsersBE
        {
            get { return _UsersBE; }
            set { _UsersBE = value; }
        }
        #endregion


        public RolList RolList
        {
            get { return _RolList; }
            set { _RolList = value; }
        }


        #region [ApplicationName]
        public System.String ApplicationName
        {
            get
            {
                return _ApplicationName;
            }
            set
            {
                _ApplicationName = value;
            }
        }
        #endregion


        #endregion



    }

    [Serializable]
    public class CreateUsersResponse : Response<Result>
    {
    }

    [XmlInclude(typeof(Result)), Serializable]
    public class Result : Entity
    {
        private Int32 _NewUserId;


		public Int32 NewUserId
		{
			get
			{
				return _NewUserId;
			}
			set
			{
				_NewUserId = value;
			}
		}
    }
    
}
