//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Prominente Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Fwk.Bases;
using System.Xml.Serialization;
using System.Xml;
using Fwk.Security.BE;
using Fwk.Security.Common;

namespace Fwk.Security.ISVC.UpdateUser
{

    [Serializable]
    public class UpdateUserReq : Request<Param>
    {
        public UpdateUserReq()
        {
            this.ServiceName = "UpdateUserService";
        }
    }
    [XmlInclude(typeof(Param)), Serializable]
    public class Param : Entity
    {
        bool _PasswordOnly = false;

        public bool PasswordOnly
        {
            get { return _PasswordOnly; }
            set { _PasswordOnly = value; }
        }
        #region [Private Members]

        ChangePassword _ChangePassword;

        public ChangePassword ChangePassword
        {
            get { return _ChangePassword; }
            set { _ChangePassword = value; }
        }
        UsersBE _UsersBE;
        private RolList _RolList = new RolList();

        private System.String _ApplicationName;


        #endregion

        #region [Properties]

        #region [Username]

        public UsersBE UsersBE
        {
            get { return _UsersBE; }
            set { _UsersBE = value; }
        }
        #endregion


        public RolList RolList
        {
            get { return _RolList; }
            set { _RolList = value; }
        }


        #region [ApplicationName]
        public System.String ApplicationName
        {
            get
            {
                return _ApplicationName;
            }
            set
            {
                _ApplicationName = value;
            }
        }
        #endregion


        #endregion



    }
    [Serializable]
    public class UpdateUserRes : Response<Result>
    {
    }

    [XmlInclude(typeof(Result)), Serializable]
    public class Result : Entity
    {
    }
    [Serializable]
    public class ChangePassword
    {


     
        string _Old;

        public string Old
        {
            get { return _Old; }
            set { _Old = value; }
        }
        string _New;

        public string New
        {
            get { return _New; }
            set { _New = value; }
        }

    }
    
}
