
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Prominente Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Fwk.Bases;
using System.Xml.Serialization;
using System.Xml;

namespace Fwk.Security.BE
{
    [XmlRoot("UsersBEList"), SerializableAttribute]
    public class UsersBEList : Entities<UsersBE>
    {
        
    }

    [XmlInclude(typeof(UsersBE)), Serializable]
    public class UsersBE : Entity
    {
        #region [Private Members]

        private System.Int32? mi_UserId;
        private System.String msz_Name;
        private System.String msz_Mail;
        private System.String msz_Password;
        private System.String _PasswordQuestion;
        private System.String _Answer;

        private System.Boolean? _ActiveFlag;
        private System.DateTime? _StartDate;
        private System.DateTime? _ModifiedDate;
        private System.Int32? _ModifiedByUserId;
   
        private System.Boolean? _IsApproved;
        private System.Boolean? _IsLockedOut;
        private System.String _FirstName;
        private System.String _LastName;
        private System.String _DNI;
        private System.Boolean _MustChangePassword;

     

 
        
        #endregion

        public UsersBE()
        {
            MustChangePassword = true;
        }

        #region [Properties]

        #region MustChangePassword
        public Boolean MustChangePassword
        {
          get { return _MustChangePassword; }
          set { _MustChangePassword = value; }
        }
        #endregion

        #region DNI
        public System.String DNI
        {
            get { return _DNI; }
            set { _DNI = value; }
        }
        #endregion

        #region [UserId]
        [XmlElement(ElementName = "UserId", DataType = "int")]
        public System.Int32? UserId
        {
            get { return mi_UserId; }
            set { mi_UserId = value; }
        }
        #endregion

        #region [Name]
        [XmlElement(ElementName = "Name", DataType = "string")]
        public System.String Name
        {
            get { return msz_Name; }
            set { msz_Name = value; }
        }
        #endregion

        #region [ActiveFlag]
        [XmlElement(ElementName = "ActiveFlag", DataType = "boolean")]
        public System.Boolean? ActiveFlag
        {
            get { return _ActiveFlag; }
            set { _ActiveFlag = value; }
        }
        #endregion

        #region [ModifiedDate]
        [XmlElement(ElementName = "ModifiedDate", DataType = "dateTime")]
        public System.DateTime? ModifiedDate
        {
            get { return _ModifiedDate; }
            set { _ModifiedDate = value; }
        }
        #endregion

        #region [CreatedDate]
        [XmlElement(ElementName = "CreatedDate", DataType = "dateTime")]
        public System.DateTime? StartDate
        {
            get { return _StartDate; }
            set { _StartDate = value; }
        }
        #endregion

        #region [ModifiedByUserId]
       
        public System.Int32? ModifiedByUserId
        {
            get { return _ModifiedByUserId; }
            set { _ModifiedByUserId = value; }
        }
        #endregion

        //#region [LastChanged]
        //[XmlIgnore]
        //public TimeSpan LastChanged
        //{
        //    get
        //    {
        //        return _LastChanged;
        //    }
        //    set
        //    {
        //        _LastChanged = value;
        //    }
        //}
        //#endregion

        //#region [XmlLastChanged]
        //[XmlElement(ElementName = "XmlLastChanged", DataType = "string")]
        //public System.String XmlLastChanged
        //{
        //    get { return XmlConvert.ToString(_LastChanged); }
        //    set { _LastChanged = XmlConvert.ToTimeSpan(value); }
        //}
        //#endregion

        #region [Password]
        [XmlElement(ElementName = "Password", DataType = "string")]
        public System.String Password
        {
            get { return msz_Password; }
            set { msz_Password = value; }
        }
        #endregion

        #region [Mail]
        [XmlElement(ElementName = "Mail", DataType = "string")]
        public System.String Mail
        {
            get { return msz_Mail; }
            set { msz_Mail = value; }
        }
        #endregion

        #region [PasswordQuestion]
        [XmlElement(ElementName = "PasswordQuestion", DataType = "string")]
        public System.String PasswordQuestion
        {
            get { return _PasswordQuestion; }
            set { _PasswordQuestion = value; }
        }
        #endregion

        #region [Answer]
        [XmlElement(ElementName = "Answer", DataType = "string")]
        public System.String Answer
        {
            get { return _Answer; }
            set { _Answer = value; }
        }
        #endregion

        #region [IsApproved]
      
        public System.Boolean? IsApproved
        {
            get { return _IsApproved; }
            set { _IsApproved = value; }
        }
        #endregion
        #region [IsLockedOut]
        public System.Boolean? IsLockedOut
        {
            get { return _IsLockedOut; }
            set { _IsLockedOut = value; }
        }
        #endregion
        
        #region [FirstName]
        [XmlElement(ElementName = "FirstName", DataType = "string")]
        public System.String FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }
        #endregion

        #region [LastName]
        [XmlElement(ElementName = "LastName", DataType = "string")]
        public System.String LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }
        #endregion


        [XmlIgnore]
        public System.String FullName
        {
            get { return string.Concat(_FirstName, ", ", _LastName); }

        }
        #endregion

        
    }
}