
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Fwk Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Fwk.Bases;
using System.Xml.Serialization;

namespace InterfaceServices.req
{


    public class ActualizarArticuloRequest : Request<ArticuloBEList>
    {
    }


    #region [BussinesData]


    public class ArticuloBEList : Entities<ArticuloBE>
    {


        #region [Methods]
        /// <summary>
        /// Metodo estatico que retorna un objeto ArticuloBEList apartir de un xml.-
        /// </summary>
        /// <param name="pXml">String con el xml</param>
        /// <returns>ArticuloBEList</returns>
        public static ArticuloBEList GetArticuloBEListFromXml(String pXml)
        {
            return (ArticuloBEList)Entity.GetObjectFromXml(typeof(ArticuloBEList), pXml);
        }
        #endregion
    }

    [XmlInclude(typeof(ArticuloBE)), Serializable]
    public class ArticuloBE : Entity
    {
        #region [Private Members]
        private String msz_Dummy;


        #endregion



        #region [Properties]

        #region [Dummy]
        [XmlElement(ElementName = "Dummy", DataType = "string")]
        public String Dummy
        {
            get { return msz_Dummy; }
            set { msz_Dummy = value; }
        }
        #endregion

        #endregion

        #region [Methods]
        /// <summary>
        /// Metodo estatico que retorna un objeto ArticuloBE apartir de un xml.-
        /// </summary>
        /// <param name="pXml">String con el xml</param>
        /// <returns>ArticuloBE</returns>
        public static ArticuloBE GetArticuloFromXml(String pXml)
        {
            return (ArticuloBE)Entity.GetObjectFromXml(typeof(ArticuloBE), pXml);
        }
        #endregion
    }







    #endregion
}
