
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Prominente Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Text;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using Fwk.Bases;
using Fwk.Exceptions;
using Fwk.Security.BE;

namespace Fwk.Security.DAC
{
    /// <summary>
    /// TableDataGateway para aspnet_RulesCategory.
    /// </summary>
    /// <Date>2009-07-01T15:14:29</Date>
    /// <Author>AAguirre</Author>
    public class RulesCategoryDAC:Fwk.Bases.BaseDAC
    {
        /// <summary>
        /// Insert
        /// </summary>
        ///<param name="paspnet_RulesCategoryBE">aspnet_RulesCategoryBE</param>
        /// <returns>void</returns>
        /// <Date>2009-07-01T15:14:29</Date>
        /// <Author>AAguirre</Author>
        public static void Insert(RulesCategoryBE pRulesCategoryBE, string pCompanyId)
        {

            Fwk.Security.FwkCategory wFwkCategory = new Fwk.Security.FwkCategory();

            try
            {
                Fwk.Security.FwkMembership.CreateCategory(wFwkCategory, pCompanyId);
              
            }
            catch (Exception ex)
            {
                throw Fwk.Exceptions.ExceptionHelper.ProcessException(ex);
            }
           
        }

        
 

        /// <summary>
        /// Delete
        /// </summary>
        ///<param name="pCategoryId">CategoryId</param>
        /// <returns>void</returns>
        /// <Date>2009-07-01T15:14:29</Date>
        /// <Author>AAguirre</Author>
        public static void Delete(System.Int32 pCategoryId, string pCompanyId)
        {
            Database wDataBase = null;
            DbCommand wCmd = null;

            try
            {
                wDataBase = DatabaseFactory.CreateDatabase(pCompanyId);
                wCmd = wDataBase.GetStoredProcCommand("dbo.aspnet_RulesCategory_d");

                /// CategoryId
                wDataBase.AddInParameter(wCmd, "CategoryId", System.Data.DbType.Int32, pCategoryId);

                wDataBase.ExecuteNonQuery(wCmd);

            }
            catch (Exception ex)
            {
                throw Fwk.Exceptions.ExceptionHelper.ProcessException(ex);
            }
            
        }

        

       


    }
}