
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Prominente Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using Fwk.Bases;
using System.Xml.Serialization;

namespace Fwk.Security.BE
{
    [XmlRoot("RulesCategoryBEList"), SerializableAttribute]
    public class RulesCategoryBEList : Entities<RulesCategoryBE>
    {
        #region [Methods]
        /// <summary>
        /// Metodo estatico que retorna un objeto aspnet_RulesCategoryList apartir de un xml.-
        /// </summary>
        /// <param name="pXml">String con el xml</param>
        /// <returns>aspnet_RulesCategoryList</returns>
        public static RulesCategoryBEList GetRulesCategoryBEListFromXml(String pXml)
        {
            return GetFromXml<RulesCategoryBEList>(pXml);
        }
        #endregion
    }

    [XmlInclude(typeof(RulesCategoryBE)), Serializable]
    public class RulesCategoryBE : Entity
    {
        #region [Private Members]
        private System.Int32? _CategoryId;
        private System.Int32? _ParentCategoryId;
        private System.String _Name;
        private System.String _ApplicationName;
        RulesBEList _RulesBEList;

        public RulesBEList RulesBEList
        {
            get { return _RulesBEList; }
            set { _RulesBEList = value; }
        }
        #endregion

        #region [Properties]

        #region [CategoryId]

        public System.Int32? CategoryId
        {
            get { return _CategoryId; }
            set { _CategoryId = value; }
        }
        #endregion
        #region [ParentCategoryId]

        public System.Int32? ParentCategoryId
        {
            get { return _ParentCategoryId; }
            set { _ParentCategoryId = value; }
        }
        #endregion
        #region [Name]
        [XmlElement(ElementName = "Name", DataType = "string")]
        public System.String Name
        {
            get { return _Name; }
            set { _Name = value; }
        }
        #endregion
        #region [ApplicationId]
       
        public System.String ApplicationName
        {
            get { return _ApplicationName; }
            set { _ApplicationName = value; }
        }
        #endregion
        #endregion

        
    }

}