
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Fwk Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Web.Security;
using Fwk.Bases;
using Fwk.Security.BE;
using Fwk.Security;
using Fwk.Security.ISVC.GetRolesForUser;


namespace Fwk.Security.SVC
{
    public class GetRolesForUserService : BusinessService<GetRolesForUserReq, GetRolesForUserRes>
    {
        public override GetRolesForUserRes Execute(GetRolesForUserReq pServiceRequest)
        {
            GetRolesForUserRes wRes = new GetRolesForUserRes ();
     

            wRes.BusinessData.RolList = FwkMembership.GetRolesForUser(pServiceRequest.BusinessData.Username, pServiceRequest.SecurityProviderName); 
            //Implement your code here
            return wRes;
        }
    }
}
        