
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Prominente Code Generator.
//     Runtime Version:1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using Fwk.Bases;
using Fwk.Security.ISVC.GetTeamByParam;
using Fwk.Security;
using Fwk.Security.BC;




namespace Fwk.Security.SVC
{

    public class GetTeamByParamService : BusinessService<GetTeamByParamRequest, GetTeamByParamResponse>
    {
        public override GetTeamByParamResponse Execute(GetTeamByParamRequest pServiceRequest)
        {
            GetTeamByParamResponse wRes = new GetTeamByParamResponse();

            if (!String.IsNullOrEmpty(pServiceRequest.BusinessData.FirstName))
            {
                pServiceRequest.BusinessData.FirstName = Fwk.Bases.Enums.GetSearchTypeValue(pServiceRequest.BusinessData.FirstName,
                                                                                             pServiceRequest.BusinessData.SearchtypeEnum);
            }

            if (!String.IsNullOrEmpty(pServiceRequest.BusinessData.LastName))
            {
                pServiceRequest.BusinessData.LastName = Fwk.Bases.Enums.GetSearchTypeValue(pServiceRequest.BusinessData.LastName,
                                                                                            pServiceRequest.BusinessData.SearchtypeEnum);
            }

            if (!String.IsNullOrEmpty(pServiceRequest.BusinessData.UserName))
            {
                pServiceRequest.BusinessData.UserName = Fwk.Bases.Enums.GetSearchTypeValue(pServiceRequest.BusinessData.UserName,
                                                                                         pServiceRequest.BusinessData.SearchtypeEnum);
            }
            TeamBC wTeamBC = new TeamBC(pServiceRequest.ContextInformation.CompanyId);
            ///TODO: mapeo de ISVC a BE
             //wRes.BusinessData = wTeamBC.GetByParam(pServiceRequest.BusinessData);


            return wRes;
        }
    }
}
